language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # - docker build -t simple-node .
  # - docker tag simple-node nguyenquangos0302app/simple-node:latest
  - docker build -t udagram-api-feed ./udagram-api-feed .
  - docker tag udagram-api-feed nguyenquangos0302app/udagram-api-feed:latest

  - docker build -t udagram-api-user ./udagram-api-user .
  - docker tag udagram-api-user nguyenquangos0302app/udagram-api-user:latest

  - docker build -t udagram-frontend ./udagram-frontend .
  - docker tag udagram-frontend nguyenquangos0302app/udagram-frontend:latest

  - docker build -t reverseproxy ./udagram-reverseproxy .
  - docker tag reverseproxy nguyenquangos0302app/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nguyenquangos0302app/udagram-api-user
  - docker push nguyenquangos0302app/udagram-api-feed
  - docker push nguyenquangos0302app/udagram-frontend
  - docker push nguyenquangos0302app/reverseproxy
